### ISSUE TITLE
Misleading documentation for cloud credentials

### ISSUE THREAD

**Issue by immesys** [heptio/velero#1286]
**What steps did you take and what happened:**

I followed the velero on aws docs which states to put your credentials in a file called velero-credentials and run:

```
kubectl create secret generic cloud-credentials \
    --namespace <VELERO_NAMESPACE> \
    --from-file cloud=credentials-velero
```

For me, this does not work because the velero manifests expect the file in the secret to be named `cloud`. So the velero-credentials file *must* be named `cloud` for it to work out of the box.

The offending part of the yaml. Note `/credentials/cloud`

```
          env:
            - name: AWS_SHARED_CREDENTIALS_FILE
              value: /credentials/cloud
            - name: VELERO_SCRATCH_DIR
              value: /scratch
            #- name: AWS_CLUSTER_NAME
            #  value: <YOUR_CLUSTER_NAME>
      volumes:
        - name: cloud-credentials
          secret:
            secretName: cloud-credentials
```
