### ISSUE TITLE
Exclude resource from backup by a standard label

### ISSUE THREAD

**Issue by brandon-mcrae-hs** [heptio/velero#1373]
**Describe the solution you'd like**
Provide a standard label that when applied to a resource will exclude that resource from being backed up.

_Example:_
```yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: do-not-backup
  namespace: default
  labels:
    # Any resource with this a standard label/value will be excluded from all backups.
    velero.io/backup-excluded: "true"
data:
  foo: {{bar}}
```

**Anything else you would like to add:**

Our specific use-case is for cluster migrations. We'd like to prevent a small subset of the resources that are created during cluster bootstrap (applying manifests via Ansible) being overwritten when we apply a restore. The restore from another cluster may include cluster-specific configuration that would be invalid in the new cluster, so there is no point in backing those resources up given that we will bootstrap them.

_Our Current solution:_
```yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-specific-config-created-at-cluster-bootstrap
  namespace: default
  labels:
    backup: "false" # Include our own standard label.
data:
  clusterSpecificData: {{cluster_specific_data}}
```
```bash
# Use a label selector to filter where backup==false
ark backup create example -l 'backup notin (false)'
```

I understand there are alternatives but this seems like a simple way for us to cherry-pick out certain resources that should not be backed up. What do you think?

**Environment:**

- Velero version (use `velero version`): 0.10.0
- Kubernetes version (use `kubectl version`): 1.10
- Kubernetes installer & version: Terraform & Ansible
- Cloud provider or hardware configuration: AWS
- OS (e.g. from `/etc/os-release`):
