### ISSUE TITLE
Velero creates ClusterRoleBinding to cluster-admin ClusterRole which does not exist on AKS

### ISSUE THREAD

**Issue by arianitu** [heptio/velero#1403]
**What steps did you take and what happened:**
Velero creates this under `00-prereqs.yaml` :

```
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: velero
  labels:
    component: velero
subjects:
  - kind: ServiceAccount
    namespace: velero
    name: velero
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
```

This role does not exist under my cluster:

`kubectl get clusterrole`:
```
NAME                                                       AGE
addon-http-application-routing-external-dns                26d
addon-http-application-routing-nginx-ingress-clusterrole   26d
omsagent-reader                                            330d
system:aggregated-metrics-reader                           42d
system:kube-dns-autoscaler                                 86d
system:metrics-server                                      239d
```

This causes the backup to fail. 

**What did you expect to happen:**
I expect there to be instructions under https://heptio.github.io/velero/v0.11.0/azure-config to create that ClusterRole.

**Anything else you would like to add:**
I am unsure if my cluster has general configuration issues due to AKS setting it up, or what's happening. 

I also noticed that another failure under my backup was `system:auth-delegator` role not found. It is being used by a ClusterRoleBinding `metrics-server:system:auth-delegator`

The original failure to run Velero was also caused by metrics-server being half run on my cluster. I did open an issue with AKS that never got addressed.

What about `cluster-admin`, is this expected to be created before velero is running?

**Environment:**
Azure AKS

- Velero version (use `velero version`): 
Client:
	Version: v1.0.0-alpha.2
	Git commit: dda76b05a8f970ee03bc7fa5bee35bef2f70127f
Server:
	Version: v1.0.0-alpha.2

- Kubernetes version (use `kubectl version`):
AKS v1.11.5

- Kubernetes installer & version:
AKS v1.11.5

- Cloud provider or hardware configuration:
AKS v1.11.5

- OS (e.g. from `/etc/os-release`):
AKS v1.11.5

**Comment by skriss** [comment]
Hmm, `cluster-admin` is a default role that's usually automatically set up -- see https://kubernetes.io/docs/reference/access-authn-authz/rbac/#default-roles-and-role-bindings and https://kubernetes.io/docs/reference/access-authn-authz/rbac/#user-facing-roles. Not sure why your cluster doesn't have it. I'm using an AKS cluster that was created within the last month, and it definitely has it created automatically.

You can manually create it with the following:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: cluster-admin
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- nonResourceURLs:
  - '*'
  verbs:
  - '*'
```
