### ISSUE TITLE
Velero Restore PVC with Reclaim Policy `Retain` got `Lost` status

### ISSUE THREAD

**Issue by bangau1** [heptio/velero#1418]
**What steps did you take and what happened:**
1. Have a storageclass with `reclaimPolicy: true` and `allowVolumeExpansion: true`
```yaml
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: expandable-retainable-standard
parameters:
  type: pd-standard
provisioner: kubernetes.io/gce-pd
allowVolumeExpansion: true
reclaimPolicy: Retain
```
2. Create a PVC with `expandable-retainable-standard` storage class
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: grafana
    chart: grafana-1.14.8
    heritage: Tiller
    release: grafana-test
  name: grafana-test
  namespace: data-devops
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: expandable-retainable-standard
``` 

3. Create a deployment and mount the volume with that pvc.
4. run velero backup `velero create backup data-devops-5 --include-namespaces data-devops`
5. delete deployment and the pvc as well
6. run velero restore `velero restore create --from-backup data-devops-5 --include-namespaces data-devops`. It took a while, like > 10 minutes (although the data in pvc is not that big). Then finish.

7.  I tried to describe the status, there's a timed out error on the pvc restoration excecution.
```
$ velero restore describe data-devops-5-20190430170224 | grep pv
  Cluster:  error waiting on in-cluster persistentvolume pvc-grafana-test-01: timed out waiting for the condition
```
8. Then I tried check the pvc status, it's **Lost**
```
==> v1/PersistentVolumeClaim
NAME          STATUS  VOLUME               CAPACITY  ACCESS MODES                    STORAGECLASS  AGE
grafana-test  Lost    pvc-grafana-test-01  0         expandable-retainable-standard  27m
```

**What did you expect to happen:**
Not sure, but I guess velero can handle the retainable volume. Or is it expected? 

**Environment:**

- Velero version (use `velero version`): 
```
Client:
	Version: v0.11.0
	Git commit: ab2fc65c02ecdcb9bb1690e3afe67a3b3196aebc
Server:
	Version: v0.11.0
```
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:38:32Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.8-gke.6", GitCommit:"394ee507d00f15a63cef577a14026096c310698e", GitTreeState:"clean", BuildDate:"2019-03-30T19:31:43Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"linux/amd64"}
```
- Kubernetes installer & version: v1.11.8-gke.6
