### ISSUE TITLE
CLI option for IAM Role in annotations

### ISSUE THREAD

**Issue by tlkamp** [heptio/velero#1581]
**Describe the solution you'd like**
Following the [AWS Config](https://velero.io/docs/v1.0.0/aws-config/) instructions for using kube2iam enabled EKS clusters, we have to edit the Velero Deployment object after it is generated, either interactively through `kubectl edit deploy/velero` or through another means (creating and applying a patch for the deployment, using a mutating admission webhook to intercept the deployment); this is not great for deploying Velero in automation. 

It would be ideal if the `velero install ...` command provided an option to set the value of the `iam.amazonaws.com/role` annotation to a given value to generate the Deployment fully.

I would like to propose a workflow like this:

```shell
velero install --provider aws \
  --aws-iam-role velero-role \
  --secret-file ./credentials-velero \
...etc
```

that results in a Deployment containing the following: 

```yaml
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
    namespace: velero
    name: velero
spec:
    replicas: 1
    template:
        metadata:
            labels:
                component: velero
            annotations:
                iam.amazonaws.com/role: velero-role
```

**Anything else you would like to add:**
If there is a better way to handle this situation, I would also be open to suggestions.

**Environment:**
AWS EKS with kube2iam

- Velero version (use `velero version`): 1.0.0
- Kubernetes version (use `kubectl version`): 1.10.13
- Kubernetes installer & version:
- Cloud provider or hardware configuration: AWS
- OS (e.g. from `/etc/os-release`): Amazon Linux 2 (CentOS)
