### ISSUE TITLE
local pv backend, cumbersome restic annotations

### ISSUE THREAD

**Issue by chrono2002** [heptio/velero#1586]
hello guys

1. is it possible to backup restic snapshots onto local pv volume (or hostpath)? maybe this would be possible in near future? for example, on baremetal it is quite cumbersome and unreliable to bring on s3 server just for backup purproses

2. why should I annotate every pod with restic volume annotations like this:
`kubectl -n nginx-example annotate -l app=nginx backup.velero.io/backup-volumes=pvc-volume,emptydir-volume`
istead of just specifying namespaces and labels via velero cli, it looks like double entry for me, why don't just make anti-affinity annotations like "do not backup this pod" or "do not backup volumes a, b, c on this pod", with backup everything in a namespace by default

**Comment by nrb** [comment]
Hi Chrono, thanks for your questions.

Our restic support is currently considered beta, and for 1.1+ we're currently working to stabilize and improve it. To answer your specific questions:

1. We've heard the request to back up to different backends besides object storage before, and it's definitely something we're considering. I don't have a timeline for this, but I do think it's important for on-prem uses cases, as you say.

2. Thanks for the suggestion! This is certainly something we can consider. (cc @carlisia)

3. Could you clarify this a little more? Are you looking for a webhook to invoke fsfreeze, or a webhook that would be invoked after fsfreeze?

**Comment by chrono2002** [comment]
3. As far as I know in Velero alongside this annotations:
```
        pre.hook.backup.velero.io/container: fsfreeze
        pre.hook.backup.velero.io/command: '["/sbin/fsfreeze", "--freeze", "/var/log/nginx"]'
        post.hook.backup.velero.io/container: fsfreeze
        post.hook.backup.velero.io/command: '["/sbin/fsfreeze", "--unfreeze", "/var/log/nginx"]'
```
you also need to write:
```
      - image: gcr.io/heptio-images/fsfreeze-pause:latest
        name: fsfreeze
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: "/var/log/nginx"
            name: nginx-logs
            readOnly: false
```
but Stash could automatically insert this part in deployments, daemonsets or statefulsets so you don't need to rewrite your manifests and just apply them
