### ISSUE TITLE
Question: Using Restore API type rather than velero CLI

### ISSUE THREAD

**Issue by ingeknudsen** [heptio/velero#1617]
This is neither a bug or a feature, but rather a question. We have discussed if we should have selective backups or selective restores, as we don't want to restore entire cluster state and need control of the sequence of which we restore the objects. We would prefer to have selective restore as it give us more power if we see we need more objects in the cluster when restore is needed. We find it easier/possible to define the backup like this:

```
apiVersion: velero.io/v1
kind: Backup
metadata:
  labels:
    velero.io/storage-location: default
  name: my-backup-secrets
  namespace: velero
spec:
  includedNamespaces:
  - '*'
  includedResources:
  - 'secrets'
  labelSelector:
    matchExpressions:
    - {key: my-app, operator: Exists}
  storageLocation: default
  ttl: 720h0m0s
  volumeSnapshotLocations:
  - default
```
... but a partial restore may look like this:
```
apiVersion: velero.io/v1
kind: Restore
metadata:
  name: my-backup-secret-20190702131209
  namespace: velero
spec:
  backupName: my-backup-all
  includedNamespaces:
  - '*'
  includedResources:
  - 'secrets'
  labelSelector:
    matchExpressions:
    - {key: my-app, operator: Exists}
```
We have noticed that only backup API type is documented here:
https://velero.io/docs/v1.0.0/api-types/

Does this mean that we should only use the cli for restore? If so, it is not clear how we use the CLI to have a matchExpressions type of label selector
