### ISSUE TITLE
sort output of resource list in `velero backup describe --details`

### ISSUE THREAD

**Issue by skriss** [heptio/velero#1731]
It would be nice to sort the resource list in `velero backup describe --details` -- both the GVK list, and then the resources within each GVK list.

**Comment by prydonius** [comment]
Do you think the list should be sorted before storing in object storage or just before displaying in the client?

**Comment by skriss** [comment]
I'd probably sort before storing - means it only has to be done once vs. every time it's read, plus then it's sorted for anyone who looks at the file directly.

**Comment by prydonius** [comment]
FYI the GVK list is already sorted, which is expected as per json.Marshal documentation

> The map keys are sorted and used as JSON object keys
https://golang.org/pkg/encoding/json/#Marshal

So the only thing we need to do is make sure that the resources within each GVK list is sorted.

**Comment by skriss** [comment]
Hmm, I'm seeing output like this (GVKs not sorted):

```
Resource List:
  apps/v1/Deployment:
    - nginx-example/nginx-deployment
    - nginx-example-2/nginx-deployment
  v1/ResourceQuota:
    - nginx-example-2/gke-resource-quotas
    - nginx-example/gke-resource-quotas
  v1/ServiceAccount:
    - nginx-example/default
    - nginx-example-2/default
  v1/Secret:
    - nginx-example-2/default-token-stqk2
    - nginx-example/default-token-k7ld2
  apps/v1/ReplicaSet:
    - nginx-example-2/nginx-deployment-fff5f96c9
    - nginx-example-2/nginx-deployment-54f4dbf9d
    - nginx-example/nginx-deployment-b7f757956
```
