### ISSUE TITLE
Create GenericAWS base struct

### ISSUE THREAD

**Issue by tomplus** [heptio/velero#193]
I use local Ceph installation as S3 compatible storage for backups and Ark works very well. However I have to define `region` which in this case is not necessary. I see that Ark needs it to create `s3url` if someone uses AWS. Or maybe you have a plan to use it somewhere in the future (support multiple regions or something) ... ?

**Comment by ncdc** [comment]
Hi @tomplus, thanks for your question. For AWS specifically, the region is required for S3 (ObjectStorageAdapter) and EBS (BlockStorageAdapter) operations. The `s3URL` is only used if you want to override aws-sdk-go's default endpoints for S3, which is necessary for something like Minio. I'm guessing you also need it for Ceph?

What happens if you specify some bogus value for region with your Ceph installation?

I can think of a couple of options:
1. Remove the requirement on `region`. I'd be concerned that people who do use AWS might accidentally omit it and it could make debugging what's wrong more difficult.
1. Add something like a `GenericAWS` ObjectStorageAdapater/BlockStorageAdapter that would then have concrete implementations for AWS, Minio, Ceph, etc. The GenericAWS base would allow the downstreams to indicate if region is required, etc.

cc @skriss @nrb @jrnt30 @dgoodwin for additional inputs.

**Comment by nrb** [comment]
I like option 2. I don't know if that could be handled via the plugin work that @skriss is currently doing, either now or in future iterations.

**Comment by ncdc** [comment]
@nrb it certainly could. For an external plugin, you would vendor in the `GenericAWS` code into your repo.

I wouldn't want to try to do this as part of the conversion to plugins, though.

**Comment by nrb** [comment]
That makes sense. Definitely easier to do once plugins are merged.

**Comment by tomplus** [comment]
@ncdc Yes, I set some bogus value and backups are stored correctly. My config:

```yaml
apiVersion: ark.heptio.com/v1
kind: Config
metadata:
  namespace: heptio-ark
  name: default
backupStorageProvider:
  bucket: backups
  aws:
    region: undef
    s3Url: http://rgw.ceph
backupSyncPeriod: 1m
gcSyncPeriod: 1m
scheduleSyncPeriod: 1m
restoreOnlyMode: false
```

I like idea of `GenericAWS` too - It would be clear and easy to use.
